# Generated by Django 3.1.4 on 2020-12-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(blank=True, default='', max_length=70)),
                ('name', models.CharField(blank=True, default='', max_length=70)),
                ('passwd', models.CharField(blank=True, default='', max_length=70)),
                ('usertype', models.CharField(blank=True, default='', max_length=70)),
            ],
        ),
    ]
